- name: setup cart server
  hosts: cart
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y 
  
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y 

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop Application User
      shell: /sbin/nologin
      system: true
      home: /app 

  - name: remove app directory if exists
    ansible.builtin.file:
      path: /app
      state: absent 

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Delete cart file if exists
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent
  
  - name: download cart Application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip
    
  - name: extract cart Application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app
  
  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: cart
      state: started
      enabled: true
      daemon_reload: true



